# Production-focused Docker Compose configuration
# Configured for using the production environment

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: 
      - .env.production
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_static:/app/backend/staticfiles
    environment:
      - PIPELINE=production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file: 
      - .env.production
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      # Make React accessible via IP address
      - HOST=0.0.0.0
      - WDS_SOCKET_HOST=localhost

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file: 
      - .env.production
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/rolltrackapp.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rolltrackapp.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - backend_static:/var/www/html/static
    depends_on:
      - frontend
      - backend

volumes:
  backend_static:
    # Named volume for Django static files